### ISSUE TITLE
Allow multiple instances on a page

### ISSUE THREAD

**Issue by bcullman** [shishkin/astro-pagefind#5]
because ID "search" is hardcoded, only 1 search box per page will attach. 

The underlying pagefind library allows one to specify the id, so that multiple searches are available on the page.

This would be useful in the situations where a search bar in a global header gives truncated results, while a dedicated search page handles longer queries (which itself would have the global header available).

**Comment by shishkin** [comment]
Hi @bcullman, thanks for bringing this use case.

ID attribute is in fact [overridable](https://github.com/shishkin/astro-pagefind/blob/main/src/components/Search.astro#L9).

However, you're right that multiple differently configured search boxes are currently not supported due to [this component passing a hardcoded data selector to the underlying library](https://github.com/shishkin/astro-pagefind/blob/main/src/components/Search.astro#L18).

I will see if I can make it work once I have some time. Feel free to submit a PR for it as well.

**Comment by shishkin** [comment]
Fixed in https://github.com/shishkin/astro-pagefind/commit/48edc2ac4e927b207e68ac898d40933727378ec6 and available in [v1.1.0](https://github.com/shishkin/astro-pagefind/releases/tag/v1.1.0). Please let me know if it works for you.
